In [200]:
import numpy as np

In [201]:
arr = np.arange(1,50)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [202]:
#method2
arr = np.array([20,30,40,50,60,70])
arr

array([20, 30, 40, 50, 60, 70])

In [203]:
#method3
arr = np.array([1,9])
arr

array([1, 9])

In [129]:
#method4
arr = np.array([1,2,3,4,5,6,7,8])
type(arr)

numpy.ndarray

In [44]:
# Creating array from list

In [204]:
#method5
list=[40,50,60,70,80,90]
np.array(list)
arr

array([1, 9])

In [205]:
type(arr)

numpy.ndarray

In [206]:
len(arr)

2

In [49]:
id(arr)

1499958986576

In [50]:
#creating array from tuple

In [207]:
#method6
tup=(2,3,4,5,6,7,8,9,0)
np.array(tup)

array([2, 3, 4, 5, 6, 7, 8, 9, 0])

In [ ]:
2.creating 1D array using numpy with 12 postive integers as arr1.

In [208]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [209]:
arr1.ndim

1

In [37]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b. Create 1D numpy array1 with 20 elements containing integers between 0 and 12 using linspace.

In [210]:
array1 = np.linspace(0,12,20)
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [ ]:
3. Find all the attributes of array1 and array2

In [14]:
#array1

In [211]:
array1 = np.array([20,30,40,50,60,70,80,90,100])


In [212]:
array1.dtype

dtype('int32')

In [213]:
array1.ndim

1

In [214]:
array1.size

9

In [215]:
array1.nbytes

36

In [216]:
array1.itemsize

4

In [217]:
array2=np.array([200,300,400,500,600,700,800,900])

In [218]:
array2.dtype

dtype('int32')

In [219]:
array2.ndim

1

In [220]:
array2.size

8

In [221]:
array2.nbytes

32

In [100]:
array2.itemsize

4

In [ ]:
4. Apply measure and describe the data(attributes and descriptive statastics) to above arrays using NumPy

In [222]:
array=np.array([8,9,0,5,6,7,8,9,0])

In [163]:
#Measure of central tendency for array1

In [223]:
array.mean()


5.777777777777778

In [224]:
np.median(array)


7.0

In [ ]:
#Measure of spread array2

In [225]:
range =np.max(array1)-min(array1) 
range

80

In [226]:
#variance
np.var(array1)

666.6666666666666

In [227]:
#standard deviation
np.std(array1)


25.81988897471611

In [228]:
#IQR

In [229]:
q1 =np.percentile(array1,25)
q1

40.0

In [230]:
q2 =np.percentile(array1,50)
q2

60.0

In [231]:
q3 = np.percentile(array1,70)
q3

76.0

In [233]:
IQR = q3-q1
IQR

36.0

In [234]:
lower_limit=q1- (1.5 * IQR)
lower_limit

-14.0

In [235]:
upper_limit =q2- (1.5 * IQR)
upper_limit 

6.0

In [236]:
array1

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

In [240]:
array>upper_limit

array([ True,  True, False, False, False,  True,  True,  True, False])